using DayTrack.Models; using DayTrack.Services; using System.Windows; using System.Windows.Controls; using System.Windows.Input;
namespace DayTrack.Windows;
public partial class WidgetWindow:Window
{
 readonly AppHost _host; TrackerSnapshot _s=new();
 public WidgetWindow(AppHost host){InitializeComponent();_host=host;_host.Collector.SnapshotChanged+=x=>{_s=x;Dispatcher.Invoke(Update);};_host.Loc.LanguageChanged+=ApplySettingsAndLocalization;Loaded+=(_,_)=>{Restore();ApplySettingsAndLocalization();};LocationChanged+=(_,_)=>Save();Closing+=(_,e)=>{e.Cancel=true;Hide();};MouseDoubleClick+=(_,_)=>_host.ShowDashboard();}
 public void ApplySettingsAndLocalization(){if(!Dispatcher.CheckAccess()){Dispatcher.Invoke(ApplySettingsAndLocalization);return;}TitleText.Text=_host.Loc.T("today");CurrentLabel.Text=_host.Loc.T("current_app");var m=_host.Settings.Current.WidgetMode;if(m=="compact"){Width=250;Height=125;CurrentPanel.Visibility=Visibility.Collapsed;AppListPanel.Visibility=Visibility.Collapsed;DetailFooter.Visibility=Visibility.Collapsed;}else if(m=="detailed"){Width=360;Height=410;CurrentPanel.Visibility=Visibility.Visible;AppListPanel.Visibility=Visibility.Visible;DetailFooter.Visibility=Visibility.Visible;}else{Width=340;Height=350;CurrentPanel.Visibility=Visibility.Visible;AppListPanel.Visibility=Visibility.Visible;DetailFooter.Visibility=Visibility.Collapsed;}Update();}
 void Update(){BigTimeText.Text=Dur(_s.TodayActiveSeconds);StateText.Text=_s.IsPaused?_host.Loc.T("paused"):_host.Loc.T("active_today");CurrentAppText.Text=string.IsNullOrWhiteSpace(_s.AppName)?"—":_s.AppName;CurrentStateText.Text=_host.Loc.T("state_"+_s.State);KeysText.Text="⌨ "+_s.TodayKeyPresses.ToString("N0");ClicksText.Text="🖱 "+_s.TodayMouseClicks.ToString("N0");TrafficText.Text="⇅ "+ExportService.Bytes(_s.TodayNetworkReceived+_s.TodayNetworkSent);AppListPanel.Children.Clear();foreach(var a in _host.Db.Apps(DateTime.Today,DateTime.Today,4)){var g=new Grid{Margin=new Thickness(2,4,2,4)};g.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1,GridUnitType.Star)});g.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var n=new TextBlock{Text=a.AppName,TextTrimming=TextTrimming.CharacterEllipsis};var t=new TextBlock{Text=Short(a.ActiveSeconds),Foreground=(System.Windows.Media.Brush)System.Windows.Application.Current.Resources["MutedTextBrush"]};Grid.SetColumn(t,1);g.Children.Add(n);g.Children.Add(t);AppListPanel.Children.Add(g);}}
 string Dur(double x)=>_host.Export.Dur(x); string Short(double x){int v=Math.Max(0,(int)x),h=v/3600,m=v%3600/60;return h>0?$"{h}:{m:00}":$"{m} {_host.Loc.T("unit_min")}";}
 void Restore(){var s=_host.Settings.Current;if(s.WidgetLeft is double left&&s.WidgetTop is double top&&double.IsFinite(left)&&double.IsFinite(top)){Left=left;Top=top;}else WindowStartupLocation=WindowStartupLocation.CenterScreen;} void Save(){if(!IsLoaded)return;if(double.IsFinite(Left)&&double.IsFinite(Top)){_host.Settings.Current.WidgetLeft=Left;_host.Settings.Current.WidgetTop=Top;}else{_host.Settings.Current.WidgetLeft=null;_host.Settings.Current.WidgetTop=null;}_host.Settings.Save();}
 void Header_MouseLeftButtonDown(object s,MouseButtonEventArgs e){if(e.LeftButton==MouseButtonState.Pressed)DragMove();} void Settings_Click(object s,RoutedEventArgs e)=>_host.ShowSettings(); void Close_Click(object s,RoutedEventArgs e)=>Hide();
}
